### ISSUE TITLE
Delicious API 用の Go パッケージ作成

### ISSUE THREAD

**Issue by tomohiro** [okinawa-go/okinawa-go.github.io#5]
### 目的

個人用ツールとしてソーシャルブックマークサイト [Delicious](http://del.icio.us) のコマンドラインツールを作りたい。(名前の候補 :delicious-cli)

今回，コマンドラインツールを作る前段階として Delicious の Web API を操作する Go のパッケージ go-delicious を開発する :muscle:

ちなみに，Go 言語で Delicious を検索したところ，壊滅状態ということがわかる :scream:
https://github.com/search?l=Go&q=delicious&type=Repositories&utf8=✓
### リソース
- [go-delicious](https://github.com/Tomohiro/go-delicious)
- [Delicious API Documentation](https://github.com/domainersuitedev/delicious-api)

**Comment by tomohiro** [comment]
Delicious の Blog 読んでると運営への不信感高まる http://blog.del.icio.us/

**Comment by tomohiro** [comment]
API リクエストの部分で Go の標準 http パッケージを利用していたが，[Sling](https://github.com/dghubble/sling) という API リクエストに特化したパッケージに切り替えようとコード書き始めたところ，JSON API にしか対応してないことが判明 (Delicious API は XML でデータが返ってくる)

書いたコードとりあえず全部投げ捨てて，地道に書き続けるしかないか  :fearful:

**Comment by tomohiro** [comment]
- API のエンドポイント消えさってる
- 新しいエンドポイント発見
- access denied なので新しいアクセストークンを発行しようとする
- アクセストークン発行するための API エンドポイントが発見できない

オワタ ／(^o^)＼

**Comment by tomohiro** [comment]
題材が悪かった

**Comment by k-nishijima** [comment]
これは残念＼(^o^)／ｵﾜﾀ
